---
title: "Homework_08"
format: html
---
# Bryan Wilcenski
# 3/4/2024
# HW 07


## Question 1

```{r}
zero_count<- function(n=1000){
  counter <- 0
  rb<- rbinom(n,1, 0.5) # create the vector
  for (i in 1:n){ #give function the number of time intervals to work through 
    if(rb[i] == 0){ #if indexed spot in the variable is equal to var, add one to counter
      counter <- counter+1
    }
  }
    return(counter)
}
zero_count()
```


## Question 2 

```{r}
#Spoke with George, asked to use this method

library(dplyr)
library(sqldf)
library(tidyr)

ID <- c(1:100)
resp<-c(rbinom(100,1,0.5))
df<- data.frame(ID,resp)

sbst_0 <- nrow(filter(df,resp==0))
sbst_0

```


## Question 3

```{r}

get_mat <- function(r=5,c=5){
  matrix<- matrix(NA, nrow = r, ncol = c)
  for (i in 1:r){
    for (j in 1:c){
      matrix[i,j]<- i*j
    }
  }
  return(matrix)
}
get_mat()

```

## Question 4

```{r}
library(ggplot2)


# a)

set.seed(27)

trt_group <- c(rep("Jackson",4),rep("Hannah",5), rep("Bryan",6))
print(trt_group)

z <- c(runif(4) + 1, runif(5) + 10, runif(6) +27)
print(z)

# combine into data frame
df <- data.frame(trt=trt_group,res=z)

# look at means in observed data
obs <- tapply(df$res,df$trt,mean)
print(obs)



# b)    shuffle and calculate mean of each group

# set up a new data frame
shuffle_data <- function(df) {
  df$res <- sample(df$res)
  means    <- tapply(df$res, df$trt, mean)
  return(means)
}

shuffle_data(df)



# c) repeat 100 times with for loop

n_reps   <- 100
results  <- data.frame(replicate = 1:n_reps, Bryan     = NA_real_, Hannah    = NA_real_, Jackson   = NA_real_)

for (i in 1:n_reps) {
  means          <- shuffle_data(df)   # returns named vector
  results$Bryan[i]   <- means["Bryan"]
  results$Hannah[i]  <- means["Hannah"]
  results$Jackson[i] <- means["Jackson"]
}

head(results)


# d)  make histogram for means of each reshuffled group

qplot(results$Bryan,   geom = "histogram", bins = 20, xlab = "Mean", ylab= "Count", main = "Bryan means")
qplot(results$Hannah,  geom = "histogram", bins = 20, xlab = "Mean", ylab= "Count", main = "Hannah means")
qplot(results$Jackson, geom = "histogram", bins = 20, xlab = "Mean", ylab= "Count", main = "Jackson means")

```



